version: '3.10'

services:
  server_folder:
    build:
      context: ./server_folder
    ports:
      - "5000:5000"
    networks:
      - app-network

  client_folder:
    build:
      context: ./client_folder
    ports:
      - "8501:8501"
    depends_on:
      - server_folder
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
